schema: 1
type: policy-context
 
id: aws-s3-bucket-is-not-configured-with-mfa-delete
name: AWS S3 bucket is not configured with MFA Delete
labels:
  - contextualization
 
csp: aws
service: s3
resource-type: bucket
 
class: risk
subclass: config
category: iam
subcategory: authentication
 
filters:
  - vendor: prisma-cloud
    policies:
      - 55486658-ae4a-4691-9eb7-a1074981fbe7
      - ed8d6416-1064-4e78-9e34-02336894df44
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "55486658-ae4a-4691-9eb7-a1074981fbe7"
      - .vendorId == "prisma-cloud" and .vendorPolicy == "ed8d6416-1064-4e78-9e34-02336894df44"
risk-config:
  default-risk: low
