schema: 1
type: policy-context
 
id: aws-cloudfront-viewer-protocol-policy-is-not-configured-with-https
name: AWS CloudFront viewer protocol policy is not configured with HTTPS
labels:
  - contextualization
 
csp: aws
service: cloudfront
resource-type: distribution
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - d183c5cd-6fe6-43a9-8fbf-6b4e44c84ec9
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "d183c5cd-6fe6-43a9-8fbf-6b4e44c84ec9"
 
risk-config:
  default-risk: high
