schema: 1
type: policy-context

id: root-object-is-not-configured
name: CloudFront distribution is not configured to return default root object
labels:
  - contextualization

csp: aws
service: cloudfront
resource-type: distribution

class: risk
subclass: config
category: iam
subcategory: public-access

filters:
  - vendor: aws-config
    policies:
      - "cloudfront-default-root-object-configured"
    match-type: any
    rules:
      - .vendorId == "aws-config" and (.vendorPolicy |contains ("cloudfront-default-root-object-configured") )

risk-config:
  default-risk: critical
