schema: 1
type: policy-context
 
id: aws-elastic-load-balancer-v2-(elbv2)-ssl-negotiation-policy-configured-with-weak-ciphers
name: AWS Elastic Load Balancer v2 (ELBv2) SSL negotiation policy configured with weak ciphers
labels:
  - contextualization
 
csp: aws
service: elb
resource-type: loadbalancer
 
class: risk
subclass: config
category: networking
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - 19eaf735-4d0e-4490-bfaf-669b8bc52d72
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "19eaf735-4d0e-4490-bfaf-669b8bc52d72"
 
risk-config:
  default-risk: medium
