schema: 1
type: policy-context
 
id: aws-emr-cluster-is-not-configured-with-cse-cmk-for-data-at-rest-encryption-(amazon-s3-with-emrfs)
name: AWS EMR cluster is not configured with CSE CMK for data at rest encryption (Amazon S3 with EMRFS)
labels:
  - contextualization
 
csp: aws
service: emr
resource-type: cluster
 
class: risk
subclass: config
category: storage
subcategory: encryption
 
filters:
  - vendor: prisma-cloud
    policies:
      - c5569c38-be41-45d9-bb79-f483ab3ec2ce
    match-type: any
    rules:
      - .vendorId == "prisma-cloud" and .vendorPolicy == "c5569c38-be41-45d9-bb79-f483ab3ec2ce"
 
risk-config:
  default-risk: medium
